// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjbj9fCxLHWhgxeVWXbMwlmiY2-G5zFgU',
    appId: '1:769590155198:web:b1d73c2a530bdf23a60bef',
    messagingSenderId: '769590155198',
    projectId: 'longrich-stockiste',
    authDomain: 'longrich-stockiste.firebaseapp.com',
    storageBucket: 'longrich-stockiste.firebasestorage.app',
    measurementId: 'G-W0ZWJC1280',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr86g1_J00XuAFcaydnfQ_yWP_4HiZs2w',
    appId: '1:769590155198:android:1e71277f09f08059a60bef',
    messagingSenderId: '769590155198',
    projectId: 'longrich-stockiste',
    storageBucket: 'longrich-stockiste.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-QhgjplQclxR4_mvSKCwDS0JHrIdG0j8',
    appId: '1:769590155198:ios:415ae3f39e60a586a60bef',
    messagingSenderId: '769590155198',
    projectId: 'longrich-stockiste',
    storageBucket: 'longrich-stockiste.firebasestorage.app',
    iosBundleId: 'com.example.longrichStockiste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-QhgjplQclxR4_mvSKCwDS0JHrIdG0j8',
    appId: '1:769590155198:ios:415ae3f39e60a586a60bef',
    messagingSenderId: '769590155198',
    projectId: 'longrich-stockiste',
    storageBucket: 'longrich-stockiste.firebasestorage.app',
    iosBundleId: 'com.example.longrichStockiste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjbj9fCxLHWhgxeVWXbMwlmiY2-G5zFgU',
    appId: '1:769590155198:web:eb170d74f714113da60bef',
    messagingSenderId: '769590155198',
    projectId: 'longrich-stockiste',
    authDomain: 'longrich-stockiste.firebaseapp.com',
    storageBucket: 'longrich-stockiste.firebasestorage.app',
    measurementId: 'G-SGED3Z609H',
  );

}